"""Add social_accounts table

Revision ID: 1e6296a1fd82
Revises: bf73ad0ffa6e
Create Date: 2024-11-30 16:32:47.544221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e6296a1fd82'
down_revision: Union[str, None] = 'bf73ad0ffa6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    schema='auth'
    )

    op.create_index('ix_social_accounts_provider_user_id', 'social_accounts', ['provider', 'provider_user_id'], schema='auth', unique=True)
    op.create_index('ix_social_accounts_user_id', 'social_accounts', ['user_id'], schema='auth')

    op.drop_column('user', 'provider', schema='auth')
    op.drop_column('user', 'provider_user_id', schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('provider', sa.String(), nullable=False), schema='auth')
    op.add_column('user', sa.Column('provider_user_id', sa.String(), nullable=False, index=True), schema='auth')

    op.drop_index('ix_social_accounts_provider_user_id', table_name='social_accounts', schema='auth')
    op.drop_index('ix_social_accounts_user_id', table_name='social_accounts', schema='auth')

    op.drop_table('social_accounts', schema='auth')
    # ### end Alembic commands ###
