name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12, 3.11, 3.12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install wemake-python-styleguide flake8 flake8-html mypy --verbose

      - name: Create report directory
        run: |
          mkdir -p flake-report

      - name: Run flake8 and generate HTML report
        run: |
          flake8 . --config=setup.cfg --format=html --htmldir=flake-report-${{ matrix.python-version }} || true

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: flake-report
          path: flake-report/

      - name: Run mypy type check
        run: |
          mypy .
